# Generated by Django 5.0.3 on 2024-06-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_extra_desgination_remove_extra_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='img',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
