# Generated by Django 5.0.3 on 2024-06-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_extra_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='pid',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='extra',
            name='img',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
