# Generated by Django 5.0.3 on 2024-06-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_user_extra_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
